name: Feature scenario
description: A step by step explanation for a proposed feature, including preconditions and context. 
title: As an  <Actor> ...
body:
- type: textarea
  id: prevalence
  attributes:
    label: Bug prevalence
    description: "How often do you or others encounter this bug?"
    placeholder: "Whenever I visit the user account page (1-2 times a week)"
  validations:
    required: true
