name: Feature scenario
description: A step by step explanation for a proposed feature, including preconditions and context. 
title: As an  <Actor> ...
body:
- type: input
  id: context_1
  attributes:
    description: "Please explain the feature step by step"
    label: "Given"
    
    placeholder: "That the User is logged in"
  validations:
    required: true
- type: input
  id: context_2
  attributes:
    description: "Please explain the feature step by step"
    label: "AND"
    
    placeholder: "They have navigated to the settings page"
  validations:
    required: false
