name: Feature scenario
description: A step by step explanation for a proposed feature, including preconditions and context. 
title: As an  <Actor> ...
body: 
- type: markdown
  label: "## Definition"
- type: textarea
  id: definition 
  attributes:
  placeholder: "Describe the entire feature in plain, non technical language here"
  value: 

