name: Feature scenario
description: A step by step explanation for a proposed feature, including preconditions and context. 
title: As an  <Actor> ...
body:
- type: markdown
  value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug!
- type: input
  id: context_1
  attributes:
    description: "provide the precondition or context required in order to execute the action"
    label: "Given"
    placeholder: "That the User is logged in"
  validations:
    required: true
    
- type: input
  id: context_2
  attributes:
    description: "provide additional preconditions here"
    label: "AND"
    placeholder: "ex. They have navigated to the settings page"
  validations:
    required: false
    
- type: input
  id: trigger
  attributes:
    description: "the action taken"
    label: "WHEN"
    placeholder: "They select the  \'Update Email\ button'"
  validations:
    required:  true 
- type: input
  id: required_action
  attributes:
    description: "an action triggered in response to the action taken"
    label: "AND"
    placeholder: "ex. The user successfully logs in again"
  validations:
    required: false
- type: input
  id: expected_action
  attributes:
    description: "The execution of the action"
    label: "THEN"
    placeholder: "ex. The User can update their email in the input field provided"
  validations:
    required: true
    
   
