name: Feature scenario
description: A step by step explanation for a proposed feature, including preconditions and context. 
title: As an  <Actor> ...
- type: markdown
  attributes:
    value: "Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord."
    preview_only: false
- type: markdown
  attributes:
    value: "This is working now!"
    

