name: Feature scenario
description: A step by step explanation for a proposed feature, including preconditions and context. 
title: As an  <Actor> ...
body:
- type: input
  id: defintion
  attributes:
    description: "Please explain the feature step by step"
    label: ## Given
    
    placeholder: "Whenever I visit the user account page (1-2 times a week)"
  validations:
    required: true
