name: Feature scenario
description: A step by step explanation for a proposed feature, including preconditions and context. 
title: As an  <Actor> ...
body:
- type: markdown
  value: "## Welcome!"
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "Break down the feature's actions into steps"
    value: |
       **Given**  that a single admin can manage multiple stations
        -  **And** each station should have it's own authentication token
        - **When** the admin is logged into their google account 
        - **And** complete the [Oauth 2.0 device flow]
        ## Desired Outcome
        **Then**  the station will be able to securely access the backend. 
      ...
    render: bash
  validations:
    required: true
