name: Feature Scenario
description: A Feature describes a single application function
labels: ["feature"]
assignees:
  - octocat
body:
- type: markdown
  attributes:
      value:|
        Please Describe the feature in descreet steps with context 
- type: input
id: Scenario
attributes:
label: Given
description: (the context within which the operation is to occur)
placeholder: ex. the User has logged in
validations:
required: true
- type: dropdown
  id: step
  attributes:
  options:
    - AND (additional context)
    - WHEN (the action is performed)
    - type: input
  attributes:
    placeholder: ex. the User has logged in
    validations:
    required: true   
  attributes:
    label: When
    description: (addition context within which the operation is to occur)
    placeholder: ex. the User has logged in
  validations:
    required: true     
