name: Feature scenario
description: A step by step explanation for a proposed feature, including preconditions and context. 
title: As an  <Actor> ...
body: 
- type: markdown
  value: "## Definition"
- type: textarea
  id: definition 
  attributes:
    label: Definition
    placeholder: "Describe the entire feature in plain, non technical language here"
    

